#!/bin/bash
# Generate Kubernetes Secret manifests from local Codebuff credentials.
#
# Usage:
#   ./scripts/generate-k8s-secrets.sh                    # print to stdout
#   ./scripts/generate-k8s-secrets.sh -o secrets.yaml    # write to file
#   ./scripts/generate-k8s-secrets.sh -n my-namespace    # custom namespace
#
# Prerequisites:
#   - Authenticated locally: `codebuff` → login
#   - Connected Claude subscription: `/connect:claude`
#   - jq installed

set -euo pipefail

# --- Defaults ---
NAMESPACE="codebuff"
OUTPUT=""
CREDENTIALS_FILE="${CODEBUFF_CREDENTIALS_FILE:-$HOME/.config/manicode/credentials.json}"

# --- Parse flags ---
usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Extracts tokens from local Codebuff credentials and generates K8s Secret YAML.

Options:
  -n, --namespace NAME    K8s namespace (default: codebuff)
  -o, --output FILE       Write YAML to file instead of stdout
  -f, --credentials FILE  Path to credentials.json (default: ~/.config/manicode/credentials.json)
  -h, --help              Show this help

Prerequisites:
  1. Authenticate locally:  codebuff  (then login via browser)
  2. Connect Claude:        /connect:claude  (in the Codebuff CLI)
  3. Install jq:            brew install jq  (or apt-get install jq)

Examples:
  $(basename "$0")                                  # Print secrets YAML to stdout
  $(basename "$0") -o k8s-secrets.yaml              # Write to file
  $(basename "$0") -n production -o secrets.yaml    # Custom namespace + file
  $(basename "$0") | kubectl apply -f -             # Apply directly
EOF
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--namespace) NAMESPACE="$2"; shift 2 ;;
    -o|--output)    OUTPUT="$2"; shift 2 ;;
    -f|--credentials) CREDENTIALS_FILE="$2"; shift 2 ;;
    -h|--help)      usage ;;
    *) echo "Unknown option: $1"; usage ;;
  esac
done

# --- Validate dependencies ---
if ! command -v jq &>/dev/null; then
  echo "❌ jq is required but not installed." >&2
  echo "   Install with: brew install jq (macOS) or apt-get install jq (Linux)" >&2
  exit 1
fi

# --- Read credentials ---
if [[ ! -f "$CREDENTIALS_FILE" ]]; then
  echo "❌ Credentials file not found: $CREDENTIALS_FILE" >&2
  echo "" >&2
  echo "   Authenticate first:" >&2
  echo "   1. Run: codebuff" >&2
  echo "   2. Login via browser" >&2
  echo "   3. Run: /connect:claude" >&2
  exit 1
fi

# Extract tokens
REFRESH_TOKEN=$(jq -r '.claudeOAuth.refreshToken // empty' "$CREDENTIALS_FILE" 2>/dev/null)
ACCESS_TOKEN=$(jq -r '.claudeOAuth.accessToken // empty' "$CREDENTIALS_FILE" 2>/dev/null)
CODEBUFF_AUTH_TOKEN=$(jq -r '.default.authToken // empty' "$CREDENTIALS_FILE" 2>/dev/null)
CODEBUFF_USER_ID=$(jq -r '.default.id // empty' "$CREDENTIALS_FILE" 2>/dev/null)
CODEBUFF_EMAIL=$(jq -r '.default.email // empty' "$CREDENTIALS_FILE" 2>/dev/null)
FINGERPRINT_ID=$(jq -r '.default.fingerprintId // empty' "$CREDENTIALS_FILE" 2>/dev/null)
FINGERPRINT_HASH=$(jq -r '.default.fingerprintHash // empty' "$CREDENTIALS_FILE" 2>/dev/null)

# --- Validate ---
WARNINGS=()

if [[ -z "$REFRESH_TOKEN" ]]; then
  echo "❌ No Claude OAuth refresh token found in credentials." >&2
  echo "" >&2
  echo "   Connect your Claude subscription first:" >&2
  echo "   1. Run: codebuff" >&2
  echo "   2. Type: /connect:claude" >&2
  echo "   3. Complete the OAuth flow in your browser" >&2
  echo "   4. Re-run this script" >&2
  exit 1
fi

if [[ -z "$CODEBUFF_AUTH_TOKEN" ]]; then
  WARNINGS+=("⚠️  No Codebuff auth token found — the codebuff-credentials Secret will be incomplete")
fi

# --- Print summary to stderr (so piping works) ---
echo "🔑 Extracting tokens from: $CREDENTIALS_FILE" >&2
echo "" >&2
echo "   Claude OAuth refresh token: ${REFRESH_TOKEN:0:12}...${REFRESH_TOKEN: -4}" >&2
if [[ -n "$ACCESS_TOKEN" ]]; then
  echo "   Claude OAuth access token:  ${ACCESS_TOKEN:0:12}...${ACCESS_TOKEN: -4}" >&2
fi
if [[ -n "$CODEBUFF_AUTH_TOKEN" ]]; then
  echo "   Codebuff auth token:        ${CODEBUFF_AUTH_TOKEN:0:8}...${CODEBUFF_AUTH_TOKEN: -4}" >&2
fi
if [[ -n "$CODEBUFF_EMAIL" ]]; then
  echo "   Codebuff account:           $CODEBUFF_EMAIL" >&2
fi
echo "   Namespace:                  $NAMESPACE" >&2
echo "" >&2

for w in "${WARNINGS[@]+"${WARNINGS[@]}"}"; do
  echo "$w" >&2
done

# --- Generate YAML ---
generate_yaml() {
  cat <<YAML
# Generated by scripts/generate-k8s-secrets.sh
# Source: $CREDENTIALS_FILE
# Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# Apply with:
#   kubectl apply -f <this-file>
#
# To regenerate after re-authenticating:
#   ./scripts/generate-k8s-secrets.sh -n $NAMESPACE -o <this-file>

---
# Claude OAuth refresh token — used by CODEBUFF_CLAUDE_OAUTH_REFRESH_TOKEN env var
# This is the key secret for K8s: enables auto-refresh of short-lived access tokens
apiVersion: v1
kind: Secret
metadata:
  name: codebuff-claude
  namespace: $NAMESPACE
  labels:
    app: codebuff
    component: claude-oauth
type: Opaque
stringData:
  refresh-token: "$REFRESH_TOKEN"

---
# Full Codebuff credentials file — mounted at ~/.config/manicode/credentials.json
# Contains Codebuff account session + Claude OAuth tokens
apiVersion: v1
kind: Secret
metadata:
  name: codebuff-credentials
  namespace: $NAMESPACE
  labels:
    app: codebuff
    component: credentials
type: Opaque
stringData:
  credentials.json: |
    {
      "default": {
        "id": "${CODEBUFF_USER_ID}",
        "name": "",
        "email": "${CODEBUFF_EMAIL}",
        "authToken": "${CODEBUFF_AUTH_TOKEN}",
        "fingerprintId": "${FINGERPRINT_ID}",
        "fingerprintHash": "${FINGERPRINT_HASH}"
      },
      "claudeOAuth": {
        "accessToken": "",
        "refreshToken": "${REFRESH_TOKEN}",
        "expiresAt": 0,
        "connectedAt": 0
      }
    }
YAML
}

# --- Output ---
if [[ -n "$OUTPUT" ]]; then
  generate_yaml > "$OUTPUT"
  echo "✅ K8s secrets written to: $OUTPUT" >&2
  echo "" >&2
  echo "   Apply with:" >&2
  echo "   kubectl apply -f $OUTPUT" >&2
else
  generate_yaml
fi
