#!/usr/bin/env bun
/**
 * Prebuild script that scans the agents/ directory and generates a TypeScript
 * module with all agent definitions embedded as static data.
 *
 * This allows agent definitions to be bundled into the cli-lite binary without
 * requiring runtime filesystem access to the agents/ directory.
 *
 * Run this before building the binary:
 *   bun run scripts/prebuild-agents.ts
 */

import * as fs from 'fs'
import * as path from 'path'

const AGENTS_DIR = path.join(import.meta.dir, '../../agents')
const OUTPUT_FILE = path.join(import.meta.dir, '../src/agents/bundled-agents.generated.ts')

interface AgentDefinition {
  id: string
  displayName?: string
  [key: string]: unknown
}

function getAllTsFiles(dir: string): string[] {
  const files: string[] = []

  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true })

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name)

      if (entry.isDirectory()) {
        if (entry.name === '__tests__' || entry.name === 'node_modules' || entry.name === 'types' || entry.name === 'e2e') {
          continue
        }
        files.push(...getAllTsFiles(fullPath))
      } else if (
        entry.isFile() &&
        entry.name.endsWith('.ts') &&
        !entry.name.endsWith('.d.ts') &&
        !entry.name.endsWith('.test.ts')
      ) {
        files.push(fullPath)
      }
    }
  } catch (error) {
    console.error(`Error reading directory ${dir}:`, error)
  }

  return files
}

async function loadAgentDefinition(filePath: string): Promise<AgentDefinition | null> {
  try {
    const module = await import(filePath)
    const definition = module.default

    if (!definition || !definition.id || !definition.model) {
      return null
    }

    const processed: AgentDefinition = { ...definition }

    if (typeof processed.handleSteps === 'function') {
      processed.handleSteps = processed.handleSteps.toString()
    }

    return processed
  } catch (error) {
    console.error(`Error loading agent from ${filePath}:`, error)
    return null
  }
}

function generateBundledAgentsFile(agents: Record<string, AgentDefinition>): string {
  const agentCount = Object.keys(agents).length

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is generated by scripts/prebuild-agents.ts
 * It contains all bundled agent definitions from the agents/ directory.
 *
 * Generated at: ${new Date().toISOString()}
 * Agent count: ${agentCount}
 */

export const bundledAgents: Record<string, any> = ${JSON.stringify(agents, null, 2)};

export function getBundledAgentIds(): string[] {
  return Object.keys(bundledAgents);
}

export function isBundledAgent(agentId: string): boolean {
  return agentId in bundledAgents;
}
`
}

async function main() {
  if (!fs.existsSync(AGENTS_DIR)) {
    console.error(`Error: agents/ directory not found at ${AGENTS_DIR}`)
    return
  }

  const tsFiles = getAllTsFiles(AGENTS_DIR)
  const agents: Record<string, AgentDefinition> = {}
  let loadedCount = 0

  for (const filePath of tsFiles) {
    const definition = await loadAgentDefinition(filePath)
    if (definition) {
      agents[definition.id] = definition
      loadedCount++
    }
  }

  const output = generateBundledAgentsFile(agents)

  const outputDir = path.dirname(OUTPUT_FILE)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8')
  console.log(`Prebundled ${loadedCount} agents into ${OUTPUT_FILE}`)
}

main().catch((error) => {
  console.error('Fatal error:', error)
  process.exit(1)
})
